#!/bin/bash

# just an assumption - the command will also work with deviating scales
# (original in the SAT Comp: 11 - probably resulted in very weak clause sharing)
n_threads_per_process=32

echo '-satsolver=CL(C){'$(($n_threads_per_process-2))'} -max-lits-per-thread=25000000 -pre-cleanup=1 \
-seed=110519 -v=2 -terminate-abruptly=1 \
-sat-overrides=templates/soc_reduce.json,templates/soc_noise.json,templates/soc_incremental.json'
