#!/bin/bash

proof_dir="proofs"
proof_working="proofs_working"
proof_logs="proofs_logs"

echo "-mono-app=SAT -pre-cleanup=1 -v=2 -satsolver=c \
 -log=$proof_logs -palrup-binary=1 -palrup-clean=1\
 -palrup=1 -proof-dir=$proof_dir \
 -palrup-check=1 -palrup-check-dir=$proof_working"
