#!/bin/bash

proof_dir="proofs"
proof_working="proofs_working"
proof_logs="proofs_logs"

## from scripts/run/mallob_local
nb_sockets=$(lscpu | grep -E "^Socket" | awk '{print $NF}')
nb_pcores_per_socket=$(lscpu | grep -E "^Core.*per socket" | awk '{print $NF}')
nb_hwthreads_per_socket=$(( $(lscpu | grep -E "^Thread.* per core" | awk '{print $NF}') * $nb_pcores_per_socket ))
nb_procs=$nb_sockets
nb_threads=$nb_pcores_per_socket
while [ $nb_threads -gt 38 ]; do
    nb_procs=$((nb_procs * 2))
    nb_threads=$((nb_threads / 2))
done

echo "-mono-app=PALRUPCHECK -pre-cleanup=1 -v=2 \
 -rpa=1 -pph=$nb_procs -log=$proof_logs -palrup-binary=1 -palrup-clean=1\
 -palrup-check=1 -palrup-check-dir=$proof_working"
