#!/bin/bash

sab_ratio=20

echo '-minprocs 2 -max-lits-per-thread=25000000 -pre-cleanup=1
 -seed=110519 -zero-only-logging=1
 -v=2 -s2f=solution.txt -terminate-abruptly=1
 -mono-app=SAT -sat-config-dirs=config/sat/base/
 -sat-config-files=config/sat/noise.json,config/sat/reduce.json
 -satsolver=CCL+[C]{'$(($sab_ratio-3))'}CCL+[C]{'$(($sab_ratio-3))'}
 -otfc=1 -otfci=1 -otfcm=1'

