#!/bin/bash

# just an assumption - the command will also work with deviating scales
# (original in the SAT Comp: 16)
n_threads_per_process=16

echo '-minprocs 2 -max-lits-per-thread=60000000 -pre-cleanup=1
 -seed=110519 -zero-only-logging=1
 -v=2 -s2f=solution.txt -terminate-abruptly=1
 -mono-app=SATWITHPRE -sat-config-dirs=config/sat/base/ 
 -sat-config-files=config/sat/noise.json,config/sat/reduce.json
 -preprocess-config=config/satwithpre/actors_all.json
 -satsolver=k_k_l+[k_]{'$(($n_threads_per_process-3))'} -jc=2
 -cjc=0 -jcup=0.05 -cjtcp=0 -fcll=2
 -sweep-max-kitten-prop=1000000
 -sweep-signal-kitten=1
 -sweep-sharing-period=0.050
 -sweep-max-iterations=999999
 -sweep-skip-ratio=0.005
 -sweep-skip-window=2.0
 -sweep-max-weak-iters=3'
