#!/bin/bash

# just an assumption - the command will also work with deviating scales
# (original in SMT Comp: 16)
n_threads_per_process=24

echo '-max-lits-per-thread=35000000 -pre-cleanup=1 -seed=110519 -zero-only-logging=1 -v=2 -s2f=solution.txt -smt-out-file=out.smt2 -terminate-abruptly=1 -mono-app=SMT -sat-config-dirs=config/sat/base/ -satsolver=CCL[C]{'$(($n_threads_per_process-3))'} -isp=1 -nsdi=3 -nsds=0 -tst=1 -js=2 -jc=2 -nisa=SATWITHPRE -preprocess-config=config/satwithpre/actors_onebulkychain.json -jcup=0.05 -pb=0 -nisd=5000 -cjc=0 -cjtcp=0 -sweep-max-kitten-prop=1000000 -sweep-signal-kitten=1 -sweep-sharing-period=0.050 -sweep-max-iterations=999999 -sweep-skip-ratio=0.005 -sweep-skip-window=2.0 -sweep-max-weak-iters=3'

# -sat-config-files=config/sat/incremental.json
